/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mant;

import database.entities.Cliente;
import database.entities.Modelo_Vehiculo;
import database.entities.Vehiculo;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.MutableComboBoxModel;
import javax.swing.table.DefaultTableModel;
import resouces.JDialogBase;
import resouces.Mensajes;
import resouces.Utilities;
import resouces.components.ComboModelo;
import resouces.interfaces.maintenance;

/**
 *
 * @author juanlht
 */
public class mnt_vehiculo extends JDialogBase implements maintenance {

    /**
     * Creates new form mnt_vehiculo
     */
    
    Vehiculo selected_vehiculo = new Vehiculo();
    public mnt_vehiculo() {
        initComponents();
        
        try{
            Connection cnn = Utilities.getConection().getConection();
            cmbColor.setConn(cnn);
            cmbColor.fillCombo("name", "colors");
            
            cmbMarca.setConn(cnn);
            cmbMarca.fillCombo("name", "marca_vehiculo");
            
            
            cmbCombus.setConn(cnn);
            cmbCombus.fillCombo("name", "combustibles");
            cmbCombus.closeConn();
            
            /*cmbModelo.setConn(cnn);
            cmbModelo.fillCombo("name", "modelo_vehiculo");
            cmbModelo.closeConn();*/

        
        }catch(SQLException e){
            Mensajes.mensajeError(new ActionEvent(this, 1, "Combos"), 
                    "ERROR LLENANDO LOS COMBOS");
        }
        
        txtYear.setLimit(4);
        txtPlaca.setLimit(7);
        txtCliente.setLimit(150);
        
    }
    
    public mnt_vehiculo(JDialogBase  parent) {
        super(parent,true);
        initComponents();
        
        try{
            Connection cnn = Utilities.getConection().getConection();
            cmbColor.setConn(cnn);
            cmbColor.fillCombo("name", "colors");
            
            cmbMarca.setConn(cnn);
            cmbMarca.fillCombo("name", "marca_vehiculo");
            
            
            cmbCombus.setConn(cnn);
            cmbCombus.fillCombo("name", "combustibles");
            cmbCombus.closeConn();
            
            /*cmbModelo.setConn(cnn);
            cmbModelo.fillCombo("name", "modelo_vehiculo");
            cmbModelo.closeConn();*/

        
        }catch(SQLException e){
            Mensajes.mensajeError(new ActionEvent(this, 1, "Combos"), 
                    "ERROR LLENANDO LOS COMBOS");
        }
        
        txtYear.setLimit(4);
        txtPlaca.setLimit(7);
        txtCliente.setLimit(150);
        
    }
    
    public mnt_vehiculo(JFrame parent) {
        super(parent,true);
        initComponents();
        
        try{
            Connection cnn = Utilities.getConection().getConection();
            cmbColor.setConn(cnn);
            cmbColor.fillCombo("name", "colors");
            
            cmbMarca.setConn(cnn);
            cmbMarca.fillCombo("name", "marca_vehiculo");
            
            
            cmbCombus.setConn(cnn);
            cmbCombus.fillCombo("name", "combustibles");
            cmbCombus.closeConn();
            
            /*cmbModelo.setConn(cnn);
            cmbModelo.fillCombo("name", "modelo_vehiculo");
            cmbModelo.closeConn();*/

        
        }catch(SQLException e){
            Mensajes.mensajeError(new ActionEvent(this, 1, "Combos"), 
                    "ERROR LLENANDO LOS COMBOS");
        }
        
        txtYear.setLimit(4);
        txtPlaca.setLimit(7);
        txtCliente.setLimit(150);
        
    }
    
    
    private void llenar_modelos(int id_marca){
        cmbModelo.removeAllItems();
        try {
            // TODO add your handling code here:
            ArrayList<Modelo_Vehiculo> list  = 
                    Modelo_Vehiculo.select(id_marca);
            for(Modelo_Vehiculo m : list){
                cmbModelo.addItem(m);
            }
        } catch (SQLException ex) {
            Logger.getLogger(mnt_vehiculo.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlLabel1 = new Main.jlLabel();
        txtPlaca = new Main.JlTextFields();
        jlLabel2 = new Main.jlLabel();
        jlLabel3 = new Main.jlLabel();
        jlLabel4 = new Main.jlLabel();
        jlLabel5 = new Main.jlLabel();
        jlLabel6 = new Main.jlLabel();
        jlLabel7 = new Main.jlLabel();
        cmbModelo = new Main.JlComboBox();
        cmbColor = new Main.JlComboBox();
        txtCliente = new Main.JlTextFields();
        chkMantenimiento = new javax.swing.JCheckBox();
        btnSeleccionar = new Main.JlButton();
        btnGrabar = new Main.JlButton();
        btnMod = new Main.JlButton();
        btnLimpiar = new Main.JlButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabVehiculo = new javax.swing.JTable();
        btnPresent = new Main.JlButton();
        btnSalir = new Main.JlButton();
        txtYear = new Main.JlTextFields();
        cmbCombus = new Main.JlComboBox();
        jButton1 = new javax.swing.JButton();
        txtIdCliente = new Main.JlTextFields();
        jlLabel8 = new Main.jlLabel();
        cmbMarca = new Main.JlComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlLabel1.setText("PLACA:");

        jlLabel2.setText("MODELO:");

        jlLabel3.setText("YEAR:");

        jlLabel4.setText("COLOR:");

        jlLabel5.setText("COMBUSTIBLE:");

        jlLabel6.setText("CLIENTE:");

        jlLabel7.setText("MANTENIMIENTO:");

        cmbModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbModeloMouseClicked(evt);
            }
        });
        cmbModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModeloActionPerformed(evt);
            }
        });
        cmbModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbModeloKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbModeloKeyPressed(evt);
            }
        });

        btnSeleccionar.setText("SELECCIONAR");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnMod.setText("MODIFICAR");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnLimpiar.setText("NUEVO");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tabVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabVehiculoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabVehiculo);

        btnPresent.setText("PRESENTAR");
        btnPresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtYear.setKind(Main.KindTextField.NUMBER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/img/lupa.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlLabel8.setText("MARCA:");

        cmbMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMarcaActionPerformed(evt);
            }
        });
        cmbMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmbMarcaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbMarcaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkMantenimiento))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbCombus, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 256, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnPresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCombus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkMantenimiento)
                            .addComponent(jlLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        Vehiculo.setVehiculo(selected_vehiculo);
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
       if(check()){
           Vehiculo v = new Vehiculo();
           v.setChapa(txtPlaca.getText());
           v.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
           v.setId_color(cmbColor.getSelectedIndex()+1);
           v.setId_combustible(cmbCombus.getSelectedIndex()+1);
           v.setId_modelo(((Modelo_Vehiculo) cmbModelo
                   .getItemAt(cmbModelo.getSelectedIndex())).getId());
           
           v.setMaintenance(chkMantenimiento.isSelected());
           v.setYear(Integer.parseInt(txtYear.getText()));
           
           try {
               v.insert(v);
           } catch (SQLException ex) {
               Logger.getLogger(mnt_vehiculo.class.getName()).
                       log(Level.SEVERE, null, ex);
               System.out.println(ex.getSQLState());
           }
           
       }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        if(check()){
           Vehiculo v = new Vehiculo();
           v.setChapa(txtPlaca.getText());
           v.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
           v.setId_color(cmbColor.getSelectedIndex()+1);
           v.setId_combustible(cmbCombus.getSelectedIndex()+1);
           v.setId_modelo(((Modelo_Vehiculo) cmbModelo
                   .getItemAt(cmbModelo.getSelectedIndex())).getId());
           v.setMaintenance(chkMantenimiento.isSelected());
           v.setYear(Integer.parseInt(txtYear.getText()));
           
           try {
               v.update(v);
           } catch (SQLException ex) {
               Logger.getLogger(mnt_vehiculo.class.getName()).
                       log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        clean();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tabVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVehiculoMouseClicked
        // TODO add your handling code here:
        selected_vehiculo.setChapa((String)tabVehiculo.getModel()
            .getValueAt(tabVehiculo.getSelectedRow(), 0));
        selected_vehiculo.setId_modelo((int)tabVehiculo.getModel()
            .getValueAt(tabVehiculo.getSelectedRow(), 1));
        selected_vehiculo.setYear((int) tabVehiculo.getModel()
            .getValueAt(tabVehiculo.getSelectedRow(), 2));
        selected_vehiculo.setId_color((int) tabVehiculo.getModel()
            .getValueAt(tabVehiculo.getSelectedRow(), 3));
        selected_vehiculo.setId_combustible((int) tabVehiculo.getModel()
            .getValueAt(tabVehiculo.getSelectedRow(), 4));
        selected_vehiculo.setId_cliente((int) tabVehiculo.getModel()
            .getValueAt(tabVehiculo.getSelectedRow(), 5));
        selected_vehiculo.setMaintenance((boolean) tabVehiculo.getModel()
            .getValueAt(tabVehiculo.getSelectedRow(), 6));
        
        llenar_campos(selected_vehiculo);
        
    }//GEN-LAST:event_tabVehiculoMouseClicked

    private void btnPresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentActionPerformed
        // TODO add your handling code here:
        fill_table(evt);
    }//GEN-LAST:event_btnPresentActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new mnt_cliente(this).setVisible(true);
        txtIdCliente.setText(Integer.toString(Cliente.getCliente().getId()));
        txtCliente.setText(Cliente.getCliente().getName());

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbModeloKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cmbModeloKeyTyped

    private void cmbModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbModeloKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbModeloKeyPressed

    private void cmbMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbMarcaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMarcaKeyTyped

    private void cmbMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbMarcaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbMarcaKeyPressed

    private void cmbMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMarcaActionPerformed
            llenar_modelos(cmbMarca.getSelectedIndex()+1);
    }//GEN-LAST:event_cmbMarcaActionPerformed

    private void cmbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModeloActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cmbModeloActionPerformed

    private void cmbModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbModeloMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbModeloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mnt_vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mnt_vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mnt_vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mnt_vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mnt_vehiculo().setVisible(true);
            }
        });
    }

    @Override
    public boolean check() {
        if(isEmpy(txtPlaca) || isEmpy(txtYear) || isEmpy(txtCliente)
                || isEmpy(txtIdCliente)||
                cmbModelo.getSelectedItem().equals(""))
            return false;
        else
            return true;
    }

    @Override
    public void clean() {
        String txt="";
        txtPlaca.setText(txt);
        txtYear.setText(txt);
        txtIdCliente.setText(txt);
        txtCliente.setText(txt);
        chkMantenimiento.setSelected(false);
        
    }

    @Override
    public void fill_table(ActionEvent evt) {
        DefaultTableModel modelo = new DefaultTableModel();
        String [] cols = {
                "PLACA", "ID_MODELO", "YEAR", "ID_COLOR",
                "ID_COMBUSTIBLE","ID_CLIENTE","MANTENIMIENTO"};
        
        for (int i=0;i<cols.length;i++)
            modelo.addColumn(cols[i]);
        
        ArrayList<Vehiculo> list = null;
        try { 
            list = Vehiculo.select();
        } catch (SQLException ex) {
            Mensajes.mensajeError(evt, "DB");
            Logger.getLogger(mnt_empleado.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
        
        int k;
            for(Vehiculo v : list){
                k=0;
                Object[] fila = new Object[7];
                fila[k++]=(Object)v.getChapa();
                fila[k++]=(Object)v.getId_modelo();
                fila[k++]=(Object)v.getYear();
                fila[k++]=(Object)v.getId_color();
                fila[k++]=(Object)v.getId_combustible();
                fila[k++]=(Object)v.getId_cliente();
                fila[k++]=(Object)v.isMaintenance();
                modelo.addRow(fila);
            }
            tabVehiculo.setModel(modelo);
    }

    @Override
    public void llenar_campos(Object e) {
        if(e instanceof Vehiculo){
            
            Vehiculo v = (Vehiculo)e;
            txtPlaca.setText(v.getChapa());
            
            try {
                Modelo_Vehiculo mv;
                mv = Modelo_Vehiculo.get(v.getId_modelo());
                cmbMarca.setSelectedIndex(mv.getId_marca_vehiculo()-1);
                llenar_modelos(mv.getId_marca_vehiculo());
                txtCliente.setText(
                        (String) Cliente.get("name", v.getId_cliente()));
                cmbModelo.setSelectedIndex(v.getId_modelo()-1);
            } catch (SQLException ex) {
                Logger.getLogger(mnt_vehiculo.class.getName()).
                        log(Level.SEVERE, null, ex);
            }
            
            
            txtYear.setText(Integer.toString(v.getYear()));
            cmbColor.setSelectedIndex(v.getId_color()-1);
            cmbCombus.setSelectedIndex(v.getId_combustible()-1);
            txtIdCliente.setText(Integer.toString(v.getId_cliente()));
            
            
            chkMantenimiento.setSelected(v.isMaintenance());
            
            
                        
            
            
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.JlButton btnGrabar;
    private Main.JlButton btnLimpiar;
    private Main.JlButton btnMod;
    private Main.JlButton btnPresent;
    private Main.JlButton btnSalir;
    private Main.JlButton btnSeleccionar;
    private javax.swing.JCheckBox chkMantenimiento;
    private Main.JlComboBox cmbColor;
    private Main.JlComboBox cmbCombus;
    private Main.JlComboBox cmbMarca;
    private Main.JlComboBox cmbModelo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private Main.jlLabel jlLabel1;
    private Main.jlLabel jlLabel2;
    private Main.jlLabel jlLabel3;
    private Main.jlLabel jlLabel4;
    private Main.jlLabel jlLabel5;
    private Main.jlLabel jlLabel6;
    private Main.jlLabel jlLabel7;
    private Main.jlLabel jlLabel8;
    private javax.swing.JTable tabVehiculo;
    private Main.JlTextFields txtCliente;
    private Main.JlTextFields txtIdCliente;
    private Main.JlTextFields txtPlaca;
    private Main.JlTextFields txtYear;
    // End of variables declaration//GEN-END:variables
}
