/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mant;

import database.entities.Articulo;
import database.entities.Articulos_Utilizados;
import database.entities.Cliente;
import database.entities.Modelo;
import database.entities.Orden;
import database.entities.Servicio;
import database.entities.Servicios_Realizados;
import database.entities.Vehiculo;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import resouces.JDialogBase;
import resouces.Mensajes;
import resouces.Utilities;
import resouces.interfaces.maintenance;

/**
 *
 * @author juanlht
 */
public class mnt_orden extends JDialogBase implements maintenance {

    /**
     * Creates new form mnt_orden
     */
    Orden selected_orden = new Orden();
    Articulos_Utilizados selected_Articulos_Utilizados =
            new Articulos_Utilizados();
    Servicios_Realizados selected_servicios_realizados =
            new Servicios_Realizados();
    
    public mnt_orden() {
        initComponents();
        rbCotizada.setSelected(true);
        panelArt.setEnabled(false);
        try 
        {
            Connection cnn = Utilities.getConection().getConection();
            cmbEstado.setConn(cnn);
            cmbEstado.fillCombo("name","estado_orden");
            
            
            cmbEstado.closeConn();
            


        } catch (SQLException ex) {
            Logger.getLogger(mnt_orden.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    
    public mnt_orden(JDialogBase parent) {
        super(parent,true);
        initComponents();
        rbCotizada.setSelected(true);
        panelArt.setEnabled(false);
        try 
        {
            Connection cnn = Utilities.getConection().getConection();
            cmbEstado.setConn(cnn);
            cmbEstado.fillCombo("name","estado_orden");
            
            
            
            
            cmbEstado.closeConn();
            


        } catch (SQLException ex) {
            Logger.getLogger(mnt_orden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public mnt_orden(JFrame parent) {
        super(parent,true);
        initComponents();
        rbCotizada.setSelected(true);
        panelArt.setEnabled(false);
        try 
        {
            Connection cnn = Utilities.getConection().getConection();
            cmbEstado.setConn(cnn);
            cmbEstado.fillCombo("name","estado_orden");
            
            
            
            
            cmbEstado.closeConn();
            


        } catch (SQLException ex) {
            Logger.getLogger(mnt_orden.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlLabel2 = new Main.jlLabel();
        jlLabel3 = new Main.jlLabel();
        cmbEstado = new Main.JlComboBox();
        btnSeleccionar = new Main.JlButton();
        btnGrabar = new Main.JlButton();
        btnMod = new Main.JlButton();
        btnLimpiar = new Main.JlButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbOrdenes = new javax.swing.JTable();
        btnPresent = new Main.JlButton();
        btnSalir = new Main.JlButton();
        btnEliminar = new Main.JlButton();
        txtPlaca = new Main.JlTextFields();
        txtVehiculo = new Main.JlTextFields();
        txtCliente = new Main.JlTextFields();
        jlLabel4 = new Main.jlLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new Main.JlTextArea();
        jButton1 = new javax.swing.JButton();
        rbListos = new javax.swing.JRadioButton();
        rbEspera = new javax.swing.JRadioButton();
        rbProceso = new javax.swing.JRadioButton();
        rbFacturadas = new javax.swing.JRadioButton();
        rbCotizada = new javax.swing.JRadioButton();
        panelArt1 = new javax.swing.JPanel();
        btnAddServ = new Main.JlButton();
        btnRemServ = new Main.JlButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbServR = new javax.swing.JTable();
        jlLabel6 = new Main.jlLabel();
        txtServName = new Main.JlTextFields();
        txtServMonto = new Main.JlTextFields();
        jButton3 = new javax.swing.JButton();
        panelArt = new javax.swing.JPanel();
        btnAddArt = new Main.JlButton();
        btnRemArt = new Main.JlButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbArtUtil = new javax.swing.JTable();
        jlLabel5 = new Main.jlLabel();
        txtArtName = new Main.JlTextFields();
        txtCant = new Main.JlTextFields();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlLabel2.setText("VEHICULO:");

        jlLabel3.setText("ESTADO:");

        btnSeleccionar.setText("SELECCIONAR");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnMod.setText("MODIFICAR");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnLimpiar.setText("NUEVO");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tbOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbOrdenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbOrdenesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbOrdenes);

        btnPresent.setText("PRESENTAR");
        btnPresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        jlLabel4.setText("DESCRIPCION:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/img/lupa.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbListos);
        rbListos.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rbListos.setText("LISTOS");
        rbListos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbListosActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbEspera);
        rbEspera.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rbEspera.setText("EN ESPERA");
        rbEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEsperaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbProceso);
        rbProceso.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rbProceso.setText("EN PROCESO");
        rbProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProcesoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFacturadas);
        rbFacturadas.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rbFacturadas.setText("FACTURADAS");
        rbFacturadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFacturadasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCotizada);
        rbCotizada.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rbCotizada.setText("COTIZADAS");
        rbCotizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCotizadaActionPerformed(evt);
            }
        });

        panelArt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAddServ.setText("AGREGAR");
        btnAddServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServActionPerformed(evt);
            }
        });

        btnRemServ.setText("REMOVER");
        btnRemServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemServActionPerformed(evt);
            }
        });

        tbServR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbServRMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbServR);

        jlLabel6.setText("SERVICIOS REALIZADOS");

        txtServName.setEditable(false);
        txtServName.setName(""); // NOI18N
        txtServName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServNameActionPerformed(evt);
            }
        });

        txtServMonto.setLimit(3);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/img/lupa.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelArt1Layout = new javax.swing.GroupLayout(panelArt1);
        panelArt1.setLayout(panelArt1Layout);
        panelArt1Layout.setHorizontalGroup(
            panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArt1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelArt1Layout.createSequentialGroup()
                        .addComponent(btnAddServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelArt1Layout.createSequentialGroup()
                            .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtServName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtServMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelArt1Layout.setVerticalGroup(
            panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArt1Layout.createSequentialGroup()
                        .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtServName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtServMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(274, 274, 274))
        );

        panelArt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAddArt.setText("AGREGAR");
        btnAddArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArtActionPerformed(evt);
            }
        });

        btnRemArt.setText("REMOVER");
        btnRemArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemArtActionPerformed(evt);
            }
        });

        tbArtUtil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbArtUtilMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbArtUtil);

        jlLabel5.setText("ARTICULOS UTILIZADOS");

        txtArtName.setEditable(false);
        txtArtName.setName(""); // NOI18N
        txtArtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtNameActionPerformed(evt);
            }
        });

        txtCant.setLimit(3);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/img/lupa.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelArtLayout = new javax.swing.GroupLayout(panelArt);
        panelArt.setLayout(panelArtLayout);
        panelArtLayout.setHorizontalGroup(
            panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelArtLayout.createSequentialGroup()
                            .addComponent(btnAddArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnRemArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelArtLayout.createSequentialGroup()
                        .addComponent(txtArtName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelArtLayout.setVerticalGroup(
            panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArtLayout.createSequentialGroup()
                        .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCotizada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbEspera)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbProceso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbListos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbFacturadas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPresent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbEspera)
                            .addComponent(rbListos)
                            .addComponent(rbProceso)
                            .addComponent(rbFacturadas)
                            .addComponent(rbCotizada))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelArt1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(panelArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        Orden.setOrden(selected_orden);
        this.dispose();
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if(check()){
            Orden o = new Orden();
            
            o.setId_vehiculo(txtPlaca.getText());
            o.setDescripcion(txtDescripcion.getText());
            o.setId_estado_orden(cmbEstado.getSelectedIndex()+1);
            try {
                o.insert(o);
            } catch (SQLException ex) {
                Logger.getLogger(mnt_vehiculo.class.getName()).
                log(Level.SEVERE, null, ex);
                System.out.println(ex.getSQLState());
            }

        }
        clean();
        fill_table(evt);
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        if(check()){
            Orden o = new Orden();
            o.setId(selected_orden.getId());
            
            o.setId_vehiculo(txtPlaca.getText());
            o.setDescripcion(txtDescripcion.getText());
            o.setId_estado_orden(cmbEstado.getSelectedIndex()+1);
            try {
                o.update(o);
            } catch (SQLException ex) {
                Logger.getLogger(mnt_vehiculo.class.getName()).
                log(Level.SEVERE, null, ex);
                System.out.println(ex.getSQLState());
            }

        }
        clean();
        fill_table(evt);
    }//GEN-LAST:event_btnModActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        clean();
        fill_table(evt);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tbOrdenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbOrdenesMouseClicked
        // TODO add your handling code here:
        selected_orden.setId((int)tbOrdenes.getModel()
            .getValueAt(tbOrdenes.getSelectedRow(), 0));
        selected_orden.setId_servicio((int)tbOrdenes.getModel()
            .getValueAt(tbOrdenes.getSelectedRow(), 1));
        selected_orden.setId_vehiculo((String) tbOrdenes.getModel()
            .getValueAt(tbOrdenes.getSelectedRow(), 2));
        selected_orden.setDescripcion((String) tbOrdenes.getModel()
            .getValueAt(tbOrdenes.getSelectedRow(), 3));
        selected_orden.setEntry_date((Date) tbOrdenes.getModel()
            .getValueAt(tbOrdenes.getSelectedRow(), 4));
        selected_orden.setId_estado_orden((int) tbOrdenes.getModel()
            .getValueAt(tbOrdenes.getSelectedRow(), 5));
        selected_orden.setDeparture_date((Date) tbOrdenes.getModel()
            .getValueAt(tbOrdenes.getSelectedRow(), 6));
        llenar_campos(selected_orden);
        fill_table_artUtil(selected_orden.getId());
        fill_table_serR(selected_orden.getId());
        if(selected_orden.getId_estado_orden()==3)
            panelArt.setVisible(true);
    }//GEN-LAST:event_tbOrdenesMouseClicked

    private void btnPresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentActionPerformed
        // TODO add your handling code here:
        fill_table(evt);
    }//GEN-LAST:event_btnPresentActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(check()){
            Orden o = new Orden();
            o.setId(selected_orden.getId());
            
            o.setId_vehiculo(txtPlaca.getText());
            o.setDescripcion(txtDescripcion.getText());
            o.setId_estado_orden(cmbEstado.getSelectedIndex()+1);
            try {
                o.delete(o);
            } catch (SQLException ex) {
                Logger.getLogger(mnt_vehiculo.class.getName()).
                log(Level.SEVERE, null, ex);
                System.out.println(ex.getSQLState());
            }

        }
        clean();
        fill_table(evt);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new mnt_vehiculo(this).setVisible(true);
        txtPlaca.setText(Vehiculo.getVehiculo().getChapa());
        try {
            txtVehiculo.setText(Modelo.get(Vehiculo.getVehiculo().
                    getChapa()).getName());
            txtCliente.setText((String)Cliente.get("name",Vehiculo.getVehiculo().getId_cliente()));
        } catch (SQLException ex) {
            Logger.getLogger(mnt_orden.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btnAddArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArtActionPerformed
        // TODO add your handling code here:
        if(!(isEmpy(txtArtName) || isEmpy(txtCant))){
            
            Articulos_Utilizados au = new Articulos_Utilizados();
            
            au.setId_articulo(Articulo.getArticulo().getId());
            au.setId_orden(selected_orden.getId());
            au.setId_cant(Integer.parseInt(txtCant.getText()));
            
            try {
                au.insert(au);
            } catch (SQLException ex) {
                Logger.getLogger(mnt_orden.class.getName())
                        .log(Level.SEVERE, null, ex);
            }
        }
        fill_table_artUtil(selected_orden.getId());
        txtArtName.setText("");
        txtCant.setText("");
    }//GEN-LAST:event_btnAddArtActionPerformed

    private void btnRemArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemArtActionPerformed
        try {
            // TODO add your handling code here:
            Articulos_Utilizados.delete(selected_Articulos_Utilizados);
        } catch (SQLException ex) {
            Logger.getLogger(mnt_orden.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
        btnRemArt.setEnabled(false);
        fill_table_artUtil(selected_orden.getId());
    }//GEN-LAST:event_btnRemArtActionPerformed

    private void txtArtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtNameActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new mnt_articulo(this).setVisible(true);
        txtArtName.setText(Articulo.getArticulo().getName());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbArtUtilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbArtUtilMouseClicked
       selected_Articulos_Utilizados.setId_orden(selected_orden.getId());
       
       selected_Articulos_Utilizados.setId_articulo((int)tbArtUtil.getModel().
               getValueAt(tbArtUtil.getSelectedRow(), 0));
       
       selected_Articulos_Utilizados.setId_cant((int)tbArtUtil.getModel().
               getValueAt(tbArtUtil.getSelectedRow(), 2));
       
       txtCant.setEnabled(true);
       btnRemArt.setEnabled(true);
        
    }//GEN-LAST:event_tbArtUtilMouseClicked

    private void rbFacturadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFacturadasActionPerformed
        // TODO add your handling code here:
        cmbEstado.setEnabled(false);
    }//GEN-LAST:event_rbFacturadasActionPerformed

    private void rbListosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbListosActionPerformed
        // TODO add your handling code here:
        cmbEstado.setEnabled(true);
    }//GEN-LAST:event_rbListosActionPerformed

    private void rbProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProcesoActionPerformed
        // TODO add your handling code here:
        cmbEstado.setEnabled(true);
    }//GEN-LAST:event_rbProcesoActionPerformed

    private void rbEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEsperaActionPerformed
        // TODO add your handling code here:
        cmbEstado.setEnabled(true);
    }//GEN-LAST:event_rbEsperaActionPerformed

    private void rbCotizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCotizadaActionPerformed
        // TODO add your handling code here:
        cmbEstado.setEnabled(true);
    }//GEN-LAST:event_rbCotizadaActionPerformed

    private void btnAddServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServActionPerformed
        // TODO add your handling code here:
        if(!isEmpy(txtServName)){
            Servicios_Realizados sr = new Servicios_Realizados();
            sr.setId_orden(selected_orden.getId());
            sr.setId_servicio(Servicio.getServicio().getId());
            
            try {
                sr.insert(sr);
            } catch (SQLException ex) {
                Logger.getLogger(mnt_orden.class.getName()).
                        log(Level.SEVERE, null, ex);
            }
        }
        fill_table_serR(selected_orden.getId());
    }//GEN-LAST:event_btnAddServActionPerformed

    private void btnRemServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemServActionPerformed
        // TODO add your handling code here:
        Servicios_Realizados sr = new Servicios_Realizados();
        sr.setId_orden(selected_orden.getId());
        sr.setId_servicio(selected_servicios_realizados.getId_servicio());
        try {
            sr.delete(sr);
        } catch (SQLException ex) {
            Logger.getLogger(mnt_orden.class.getName()).log(Level.SEVERE, null, ex);
        }
        fill_table_serR(selected_orden.getId());
    }//GEN-LAST:event_btnRemServActionPerformed

    private void tbServRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbServRMouseClicked
        // TODO add your handling code here:
        selected_servicios_realizados.setId_orden(selected_orden.getId());
       
       selected_servicios_realizados.setId_servicio((int)tbServR.getModel().
               getValueAt(tbServR.getSelectedRow(), 0));
       
       
       btnRemServ.setEnabled(true);
       
    }//GEN-LAST:event_tbServRMouseClicked

    private void txtServNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServNameActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new mnt_servicio(this).setVisible(true);
        txtServName.setText(Servicio.getServicio().getName());
        txtServMonto.setText(Double.toString(Servicio.getServicio().getCost()));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mnt_orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mnt_orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mnt_orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mnt_orden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mnt_orden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.JlButton btnAddArt;
    private Main.JlButton btnAddServ;
    private Main.JlButton btnEliminar;
    private Main.JlButton btnGrabar;
    private Main.JlButton btnLimpiar;
    private Main.JlButton btnMod;
    private Main.JlButton btnPresent;
    private Main.JlButton btnRemArt;
    private Main.JlButton btnRemServ;
    private Main.JlButton btnSalir;
    private Main.JlButton btnSeleccionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private Main.JlComboBox cmbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private Main.jlLabel jlLabel2;
    private Main.jlLabel jlLabel3;
    private Main.jlLabel jlLabel4;
    private Main.jlLabel jlLabel5;
    private Main.jlLabel jlLabel6;
    private javax.swing.JPanel panelArt;
    private javax.swing.JPanel panelArt1;
    private javax.swing.JRadioButton rbCotizada;
    private javax.swing.JRadioButton rbEspera;
    private javax.swing.JRadioButton rbFacturadas;
    private javax.swing.JRadioButton rbListos;
    private javax.swing.JRadioButton rbProceso;
    private javax.swing.JTable tbArtUtil;
    private javax.swing.JTable tbOrdenes;
    private javax.swing.JTable tbServR;
    private Main.JlTextFields txtArtName;
    private Main.JlTextFields txtCant;
    private Main.JlTextFields txtCliente;
    private Main.JlTextArea txtDescripcion;
    private Main.JlTextFields txtPlaca;
    private Main.JlTextFields txtServMonto;
    private Main.JlTextFields txtServName;
    private Main.JlTextFields txtVehiculo;
    // End of variables declaration//GEN-END:variables

    
    public void fill_table_artUtil(int id_orden){
        DefaultTableModel modelo = new DefaultTableModel();
        String [] cols = {
                "ID_ARTICULO", "NOMBRE", "CANT"};
        
        for (int i=0;i<cols.length;i++)
            modelo.addColumn(cols[i]);
        
        ArrayList<Articulos_Utilizados> list = null;
        
        try { 
            list = Articulos_Utilizados.select(id_orden);  
        } catch (SQLException ex) {
            Mensajes.mensajeError(new 
        ActionEvent(this, 1,"Error llenando la tabla" ), "DB");
            Logger.getLogger(mnt_empleado.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
        
        int k;
            for(Articulos_Utilizados s : list){
                k=0;
                Object[] fila = new Object[3];
                fila[k++]=(Object)s.getId_articulo();
                fila[k++]=(Object)s.getNombre_articulo();
                fila[k++]=(Object)s.getCant();
                
                modelo.addRow(fila);
            }
            tbArtUtil.setModel(modelo);
    }
    
    public void fill_table_serR(int id_orden){
        DefaultTableModel modelo = new DefaultTableModel();
        String [] cols = {
                "ID", "NOMBRE", "PRECIO"};
        
        for (int i=0;i<cols.length;i++)
            modelo.addColumn(cols[i]);
        
        ArrayList<Servicio> list = null;
        
        try { 
            list = Servicios_Realizados.select(id_orden);  
        } catch (SQLException ex) {
            Mensajes.mensajeError(new 
        ActionEvent(this, 1,"Error llenando la tabla" ), "DB");
            Logger.getLogger(mnt_empleado.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
        
        int k;
            for(Servicio s : list){
                k=0;
                Object[] fila = new Object[3];
                fila[k++]=(Object)s.getId();
                fila[k++]=(Object)s.getName();
                fila[k++]=(Object)s.getCost();
                
                modelo.addRow(fila);
            }
            tbServR.setModel(modelo);
    }
    
    @Override
    public boolean check() {
        if(isEmpy(txtPlaca) || isEmpy(txtCliente) || 
                txtDescripcion.getText().isEmpty() || isEmpy(txtVehiculo))
            return false;
        else
            return true;       
    }

    @Override
    public void clean() {
        String txt = "";
        txtCliente.setText(txt);
        txtDescripcion.setText(txt);
        txtPlaca.setText(txt);
        txtVehiculo.setText(txt);
        panelArt.setEnabled(false);
    }

    @Override
    public void fill_table(ActionEvent evt) {
        DefaultTableModel modelo = new DefaultTableModel();
        String [] cols = {
                "ID", "SERVICIO", "VEHICULO","DESCRIPCION", "ENTRADA",
                "ESTADO","SALIDA"};
        
        for (int i=0;i<cols.length;i++)
            modelo.addColumn(cols[i]);
        
        ArrayList<Orden> list = null;
        try { 
            
            if(rbCotizada.isSelected())
                list = Orden.select(1);
            else if(rbEspera.isSelected())
                list = Orden.select(2);
            else if(rbProceso.isSelected())
                list = Orden.select(3);
            else if(rbListos.isSelected())
                list = Orden.select(4);
            else if(rbFacturadas.isSelected())  
                list = Orden.select(5);
            
            
        } catch (SQLException ex) {
            Mensajes.mensajeError(evt, "DB");
            Logger.getLogger(mnt_empleado.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
        
        int k;
            for(Orden s : list){
                k=0;
                Object[] fila = new Object[7];
                fila[k++]=(Object)s.getId();
                fila[k++]=(Object)s.getId_servicio();
                fila[k++]=(Object)s.getId_vehiculo();
                fila[k++]=(Object)s.getDescripcion();
                fila[k++]=(Object)s.getEntry_date();
                fila[k++]=(Object)s.getId_estado_orden();
                fila[k++]=(Object)s.getDeparture_date();
                modelo.addRow(fila);
            }
            tbOrdenes.setModel(modelo);
    }

    @Override
    public void llenar_campos(Object e) {
        if(e instanceof Orden){
            Orden or = (Orden)e;
            
            txtPlaca.setText(or.getId_vehiculo());
            txtDescripcion.setText(or.getDescripcion());
            
            try {
                
                txtVehiculo.setText(Modelo.get(or.getId_vehiculo()).getName());
                txtCliente.setText((String)Cliente.get
                ("name",Vehiculo.get(or.getId_vehiculo()).getId_cliente()));
            } catch (SQLException ex) {
                Logger.getLogger(mnt_orden.class.getName()).
                        log(Level.SEVERE, null, ex);
            }
            cmbEstado.setSelectedIndex(or.getId_estado_orden()-1);
            
            
        }
    }
}
