/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mant;

import com.sun.glass.events.KeyEvent;
import database.DB;
import database.entities.Articulo;
import database.entities.Articulos_Utilizados;
import database.entities.Caja;
import database.entities.Empleados;
import database.entities.Modelo;
import database.entities.Orden;
import database.entities.Servicio;
import database.entities.Servicios_Realizados;
import database.entities.Trans;
import database.entities.Vehiculo;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeMath.round;
import net.sf.jasperreports.engine.JRException;
import reports.factura.FacturaDataSource;
import resouces.AbstractJasperReports;
import resouces.JDialogBase;
import resouces.Mensajes;
import resouces.Utilities;

/**
 *
 * @author juanlht
 */
public class mnt_cotizacion extends JDialogBase {

    /**
     * Creates new form mnt_facturacion
     */
    Orden selected_orden = new Orden();
    Articulos_Utilizados selected_Articulos_Utilizados =
            new Articulos_Utilizados();
    Servicios_Realizados selected_servicios_realizados =
            new Servicios_Realizados();
    ArrayList<Trans> tList = new ArrayList<>();
    ArrayList<Articulos_Utilizados> Artlist = new ArrayList<>();
    ArrayList<Servicio> Servlist = new ArrayList<>();
    
    public mnt_cotizacion() {
        initComponents();
        
        try {
            selected_orden.insert_cotizacion(selected_orden);
        } catch (SQLException ex) {
            Logger.getLogger(mnt_cotizacion.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }
    
    
    public mnt_cotizacion(JDialogBase parent) {
        super(parent,true);
        initComponents();
        try {
            selected_orden.insert_cotizacion(selected_orden);
        } catch (SQLException ex) {
            Logger.getLogger(mnt_cotizacion.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }
    
     public mnt_cotizacion(JFrame parent) {
        super(parent,true);
        initComponents();
        try {
            selected_orden.insert_cotizacion(selected_orden);
        } catch (SQLException ex) {
            Logger.getLogger(mnt_cotizacion.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new Main.JlTextArea();
        txtMonto = new Main.JlTextFields();
        jlLabel2 = new Main.jlLabel();
        jlButton1 = new Main.JlButton();
        jlButton2 = new Main.JlButton();
        panelArt1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbServR = new javax.swing.JTable();
        jlLabel6 = new Main.jlLabel();
        btnAddServ = new Main.JlButton();
        btnRemServ = new Main.JlButton();
        txtServMonto = new Main.JlTextFields();
        txtServName = new Main.JlTextFields();
        jButton3 = new javax.swing.JButton();
        panelArt = new javax.swing.JPanel();
        btnAddArt = new Main.JlButton();
        btnRemArt = new Main.JlButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbArtUtil = new javax.swing.JTable();
        jlLabel5 = new Main.jlLabel();
        txtArtName = new Main.JlTextFields();
        txtCant = new Main.JlTextFields();
        jButton2 = new javax.swing.JButton();
        txtPorcent = new Main.JlTextFields();
        jlLabel3 = new Main.jlLabel();
        jlButton3 = new Main.JlButton();
        jlLabel4 = new Main.jlLabel();
        jlLabel7 = new Main.jlLabel();
        txtNombre = new Main.JlTextFields();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jlLabel2.setText("MONTO TOTAL:");

        jlButton1.setText("IMPRIMIR");
        jlButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlButton1ActionPerformed(evt);
            }
        });

        jlButton2.setText("CANCELAR");
        jlButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlButton2ActionPerformed(evt);
            }
        });

        panelArt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbServR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbServRMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbServR);

        jlLabel6.setText("SERVICIOS REALIZADOS");

        btnAddServ.setText("AGREGAR");
        btnAddServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServActionPerformed(evt);
            }
        });

        btnRemServ.setText("REMOVER");
        btnRemServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemServActionPerformed(evt);
            }
        });

        txtServMonto.setLimit(3);

        txtServName.setEditable(false);
        txtServName.setName(""); // NOI18N
        txtServName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServNameActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/img/lupa.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelArt1Layout = new javax.swing.GroupLayout(panelArt1);
        panelArt1.setLayout(panelArt1Layout);
        panelArt1Layout.setHorizontalGroup(
            panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArt1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelArt1Layout.createSequentialGroup()
                            .addComponent(btnAddServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnRemServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelArt1Layout.createSequentialGroup()
                        .addComponent(txtServName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtServMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelArt1Layout.setVerticalGroup(
            panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArt1Layout.createSequentialGroup()
                        .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtServName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtServMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(panelArt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelArt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnAddArt.setText("AGREGAR");
        btnAddArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArtActionPerformed(evt);
            }
        });

        btnRemArt.setText("REMOVER");
        btnRemArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemArtActionPerformed(evt);
            }
        });

        tbArtUtil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbArtUtilMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbArtUtil);

        jlLabel5.setText("ARTICULOS UTILIZADOS");

        txtArtName.setEditable(false);
        txtArtName.setName(""); // NOI18N
        txtArtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtNameActionPerformed(evt);
            }
        });

        txtCant.setLimit(3);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/img/lupa.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtPorcent.setText("30");
        txtPorcent.setKind(Main.KindTextField.NUMBER);
        txtPorcent.setLimit(2);
        txtPorcent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPorcentActionPerformed(evt);
            }
        });
        txtPorcent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPorcentKeyPressed(evt);
            }
        });

        jlLabel3.setText("%:");

        javax.swing.GroupLayout panelArtLayout = new javax.swing.GroupLayout(panelArt);
        panelArt.setLayout(panelArtLayout);
        panelArtLayout.setHorizontalGroup(
            panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtLayout.createSequentialGroup()
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelArtLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelArtLayout.createSequentialGroup()
                                .addComponent(txtArtName, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelArtLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPorcent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelArtLayout.setVerticalGroup(
            panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelArtLayout.createSequentialGroup()
                        .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorcent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jlButton3.setText("LIMPIAR");
        jlButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlButton3ActionPerformed(evt);
            }
        });

        jlLabel4.setText("DESCRIPCION");

        jlLabel7.setText("NOMBRE CLIENTE");

        txtNombre.setLimit(50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jlLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelArt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jlLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jlLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelArt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArtActionPerformed
        // TODO add your handling code here:
        if(!(isEmpy(txtArtName) || isEmpy(txtCant))){

            Articulos_Utilizados au = new Articulos_Utilizados();
            au.setId_articulo(Articulo.getArticulo().getId());
            au.setId_orden(selected_orden.getId());
            au.setId_cant(Integer.parseInt(txtCant.getText()));
            au.setCost(Articulo.getArticulo().getCost());
            Artlist.add(au);
        }
        fill_table_artUtil(txtPorcent.getText());
        txtArtName.setText("");
        txtCant.setText("");
        txtMonto.setText(Double.toString(calcular_monto()));
    }//GEN-LAST:event_btnAddArtActionPerformed

    private void btnRemArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemArtActionPerformed
        Artlist.remove(selected_Articulos_Utilizados);
        btnRemArt.setEnabled(false);
        fill_table_artUtil(txtPorcent.getText());
        txtMonto.setText(Double.toString(calcular_monto()));
    }//GEN-LAST:event_btnRemArtActionPerformed

    private void tbArtUtilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbArtUtilMouseClicked
        selected_Articulos_Utilizados.setId_orden(selected_orden.getId());

        selected_Articulos_Utilizados.setId_articulo((int)tbArtUtil.getModel().
            getValueAt(tbArtUtil.getSelectedRow(), 0));

        selected_Articulos_Utilizados.setId_cant((int)tbArtUtil.getModel().
            getValueAt(tbArtUtil.getSelectedRow(), 2));

        txtCant.setEnabled(true);
        btnRemArt.setEnabled(true);

    }//GEN-LAST:event_tbArtUtilMouseClicked

    private void txtArtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtNameActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new mnt_articulo(this).setVisible(true);
        txtArtName.setText(Articulo.getArticulo().getName());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbServRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbServRMouseClicked
        // TODO add your handling code here:
        selected_servicios_realizados.setId_orden(selected_orden.getId());

        selected_servicios_realizados.setId_servicio((int)tbServR.getModel().
            getValueAt(tbServR.getSelectedRow(), 0));

       
    }//GEN-LAST:event_tbServRMouseClicked

    private void txtPorcentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPorcentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPorcentActionPerformed

    private void txtPorcentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPorcentKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==10){//enter
            fill_table_artUtil( txtPorcent.getText());
            txtMonto.setText(Double.toString(calcular_monto()));
        }
    }//GEN-LAST:event_txtPorcentKeyPressed

    private void jlButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
      
    }//GEN-LAST:event_jlButton2ActionPerformed

    private void jlButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlButton1ActionPerformed
        // TODO add your handling code here:
        
        if(txtNombre.getText().isEmpty() || txtDescripcion.getText().isEmpty()){
            Mensajes.mensajeError(evt, "NO DEBE DEJAR CAMPOS VACIOS");
            return ;
        }
            
        
        
        
        int count= 0;
        System.out.println(selected_orden.getId_estado_orden());
        
        int artRows = tbArtUtil.getModel().getRowCount();
        int serRows = tbServR.getModel().getRowCount();
        Double montoArt=0.0,montoServ=0.0;
        
        for(int x=0; x<artRows; x++){
            int id_area_articulo=0;
            int id_articulo = (int)tbArtUtil.getModel().getValueAt(x, 0);
            int cant = (int)tbArtUtil.getModel().getValueAt(x, 2);
            Double precio = Double.parseDouble(""+tbArtUtil.getModel().getValueAt(x, 3));
            
            try {
                id_area_articulo = (int)Articulo.get(id_articulo, "id_area");
            } catch (SQLException ex) {
                Logger.getLogger(mnt_cotizacion.class.getName()).
                        log(Level.SEVERE, null, ex);
            }
            Trans t = new Trans();
            t.setId_tipo_trans(4);//ventas de articulos
            t.setId_area(id_area_articulo);
            t.setCantidad(cant);
            t.setValor(precio);
            t.setTotal(cant*precio);
            t.setRef_tran(Integer.toString(id_articulo));
            t.setId_resource(Integer.toString(selected_orden.getId()));
            tList.add(t);
            count++;    
        }
        
        for(int x=0; x<serRows; x++){  
            int id_area_servicio = 0;
            int id_servicio = (int)tbServR.getModel().getValueAt(x, 0);
            Double precio = Double.parseDouble(""+tbServR.getModel().getValueAt(x, 2));
            try {
                id_area_servicio = Servicio.get(id_servicio).getId_area();
            } catch (SQLException ex) {
                Logger.getLogger(mnt_cotizacion.class.getName()).
                        log(Level.SEVERE, null, ex);
            }
            
            Trans t = new Trans();
            t.setId_tipo_trans(3);//cobros por servicios
            t.setId_area(id_area_servicio);
            t.setCantidad(1);
            t.setValor(precio);
            t.setTotal(precio);
            t.setRef_tran(Integer.toString(id_servicio));
            t.setId_resource(Integer.toString(selected_orden.getId()));
            tList.add(t);
            count++;
            
        }
        System.out.println(count);
        if(count>0){
           
            
            InputStream path = this.getClass().getResourceAsStream("/reports/factura/Factura.jasper");
            System.out.println("Path input stream---> "+path.toString());
            FacturaDataSource datasource = new FacturaDataSource(tList);
            Map parametros = new HashMap();
            parametros.put("TOTAL_PAGAR",Double.toString(calcular_monto()));
            parametros.put("NOMBRE_CLIENTE","CLIENTE \n"+txtNombre.getText());
            parametros.put("DESCRIPCION",txtDescripcion.getText());
            parametros.put("COTIZACION", "COTIZACION # "+selected_orden.getId());
            AbstractJasperReports jasper = null;
            try {
                jasper = new AbstractJasperReports(datasource,path,parametros);
            } catch (JRException ex) {
                Logger.getLogger(mnt_cotizacion.class.getName())
                        .log(Level.SEVERE, null, ex);
            }
            /*JFileChooser fChooser = new JFileChooser();
            fChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int result = fChooser.showSaveDialog(new Frame());
            if(result == JFileChooser.APPROVE_OPTION){
                File createdFile = fChooser.getSelectedFile();
                String path_report = createdFile.getAbsolutePath()+File.separator+selected_orden.getId()+"_COTIZACION.pdf";
                try {
                    jasper.exportToPdf(path_report);
                } catch (JRException ex) {
                    Logger.getLogger(mnt_cotizacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }*/
            jasper.showViewer();
            String descripcion = txtNombre.getText()+"\n"+txtDescripcion.getText()+"\n PARA UN TOTAL DE: "
                    +txtMonto.getText();
            selected_orden.setDescripcion(descripcion);
            try {
                selected_orden.update_cotizacion(selected_orden);
            } catch (SQLException ex) {
                Logger.getLogger(mnt_cotizacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }      
        
    }//GEN-LAST:event_jlButton1ActionPerformed

    private void jlButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlButton3ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jlButton3ActionPerformed

    private void btnAddServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServActionPerformed
        // TODO add your handling code here:
        if(!isEmpy(txtServName)){
            Servicio sr = new Servicio();
            sr.setId(Servicio.getServicio().getId());
            sr.setName(Servicio.getServicio().getName());
            sr.setCost(Servicio.getServicio().getCost());
           
            Servlist.add(sr);
            
        }
        fill_table_serR(selected_orden.getId());
        txtMonto.setText(Double.toString(calcular_monto()));
        txtMonto.setText(Double.toString(calcular_monto()));
    }//GEN-LAST:event_btnAddServActionPerformed

    private void btnRemServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemServActionPerformed
        // TODO add your handling code here:
        
        Servicio s = new Servicio();
        s.setId(selected_servicios_realizados.getId_servicio());
        Servlist.remove(s);
        fill_table_serR(selected_orden.getId());
    }//GEN-LAST:event_btnRemServActionPerformed

    private void txtServNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServNameActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new mnt_servicio(this).setVisible(true);
        txtServName.setText(Servicio.getServicio().getName());
        txtServMonto.setText(Double.toString(Servicio.getServicio().getCost()));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mnt_cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mnt_cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mnt_cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mnt_cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mnt_cotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Main.JlButton btnAddArt;
    private Main.JlButton btnAddServ;
    private Main.JlButton btnRemArt;
    private Main.JlButton btnRemServ;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private Main.JlButton jlButton1;
    private Main.JlButton jlButton2;
    private Main.JlButton jlButton3;
    private Main.jlLabel jlLabel2;
    private Main.jlLabel jlLabel3;
    private Main.jlLabel jlLabel4;
    private Main.jlLabel jlLabel5;
    private Main.jlLabel jlLabel6;
    private Main.jlLabel jlLabel7;
    private javax.swing.JPanel panelArt;
    private javax.swing.JPanel panelArt1;
    private javax.swing.JTable tbArtUtil;
    private javax.swing.JTable tbServR;
    private Main.JlTextFields txtArtName;
    private Main.JlTextFields txtCant;
    private Main.JlTextArea txtDescripcion;
    private Main.JlTextFields txtMonto;
    private Main.JlTextFields txtNombre;
    private Main.JlTextFields txtPorcent;
    private Main.JlTextFields txtServMonto;
    private Main.JlTextFields txtServName;
    // End of variables declaration//GEN-END:variables

    public void fill_table_artUtil(String porcentaje_gan){
        DecimalFormat df = new DecimalFormat("#");
        
        DefaultTableModel modelo = new DefaultTableModel();
        String [] cols = {
                "ID_ARTICULO", "NOMBRE", "CANT" , "PRECIO","TOTAL"};
        
        for (int i=0;i<cols.length;i++)
            modelo.addColumn(cols[i]);
        
        
        
        
        
        int k;
            for(Articulos_Utilizados s : Artlist){
                k=0;
                Object[] fila = new Object[5];
                fila[k++]=(Object)s.getId_articulo();
                fila[k++]=(Object)s.getNombre_articulo();
                fila[k++]=(Object)s.getCant();
                Float precio = Float.parseFloat(df.format((s.getCost()+s.getCost()*(Float.parseFloat("0."+porcentaje_gan)))));
                fila[k++]=(Object)precio;
                fila[k++]=(Object)(s.getCant()* precio);
                modelo.addRow(fila);
            }
            tbArtUtil.setModel(modelo);
    }
    
    public void fill_table_serR(int id_orden){
        DefaultTableModel modelo = new DefaultTableModel();
        String [] cols = {
                "ID", "NOMBRE", "PRECIO"};
        
        for (int i=0;i<cols.length;i++)
            modelo.addColumn(cols[i]);
        
        
        
        
        
        int k;
            for(Servicio s : Servlist){
                k=0;
                Object[] fila = new Object[3];
                fila[k++]=(Object)s.getId();
                fila[k++]=(Object)s.getName();
                fila[k++]=(Object)s.getCost();
                
                modelo.addRow(fila);
            }
            tbServR.setModel(modelo);
    }
    
    private double calcular_monto(){
        int artRows = tbArtUtil.getModel().getRowCount();
        int serRows = tbServR.getModel().getRowCount();
        Double montoArt=0.0,montoServ=0.0;
      
        
        for(int x=0; x<artRows; x++){
            montoArt = montoArt+(Float)tbArtUtil.getModel().getValueAt(x, 4);
        }
        
        for(int x=0; x<serRows; x++){
            montoServ = montoServ+(Double)tbServR.getModel().getValueAt(x, 2);
        }
        
        
        return  montoArt+montoServ;
    }
    
    private void clear(){
        String txt = "";
        txtArtName.setText(txt);
        txtCant.setText(txt);
        txtDescripcion.setText(txt);
        txtMonto.setText(txt);
        tbArtUtil.setModel(new DefaultTableModel());
        tbServR.setModel(new DefaultTableModel());
    }

}
