/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reports.informativos;

import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import mant.mnt_cotizacion;
import net.sf.jasperreports.engine.JRException;
import reports.factura.FacturaDataSource;
import resouces.AbstractJasperReports;
import resouces.Utilities;

/**
 *
 * @author juanlht
 */
public class reportesInformativos extends JDialog {

    /**
     * Creates new form reportesInformativos
     */
    public reportesInformativos() {
        initComponents();
    }
    
    public reportesInformativos(JFrame parent) {
        super(parent,true);
        initComponents();
    }
    
    public reportesInformativos(JDialog parent) {
        super(parent,true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbRep = new Main.JlComboBox();
        jlButton1 = new Main.JlButton();
        Dp1 = new org.jdesktop.swingx.JXDatePicker();
        Dp2 = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbRep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Registros de gastos del negocio", "Lo que se cotizo que no se facturo" }));

        jlButton1.setText("Mostrar");
        jlButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Dp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(cmbRep, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jlButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(cmbRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jlButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlButton1ActionPerformed
        RegGastoDataSource datasource = null;
        RepOrdenCotizada cotSource = null;   
            if(cmbRep.getSelectedIndex()==0){
                if(Dp1.getDate()==null && Dp2.getDate()==null)
                    datasource = new RegGastoDataSource();
                else
                    datasource = new RegGastoDataSource(Utilities.getJxDate(Dp1)
                            ,Utilities.getJxDate(Dp2));
                
                InputStream path = this.getClass().getResourceAsStream
                ("/reports/informativos/reporteGastos.jasper");
                System.out.println("Path input stream---> "+path.toString());
                AbstractJasperReports jasper = null;
                try {
                    jasper = new AbstractJasperReports(datasource,path,null);
                } catch (JRException ex) {
                    Logger.getLogger(mnt_cotizacion.class.getName())
                            .log(Level.SEVERE, null, ex);
                }

                jasper.showViewer();
            }
            else{
                if(Dp1.getDate()==null && Dp2.getDate()==null)
                    cotSource = new RepOrdenCotizada();
                else
                    cotSource = new RepOrdenCotizada(Utilities.getJxDate(Dp1),
                    Utilities.getJxDate(Dp2));
                InputStream path = this.getClass().getResourceAsStream
                ("/reports/informativos/reporteCotizados.jasper");
                System.out.println("Path input stream---> "+path.toString());
                AbstractJasperReports jasper = null;
                try {
                    jasper = new AbstractJasperReports(cotSource,path,null);
                } catch (JRException ex) {
                    Logger.getLogger(mnt_cotizacion.class.getName())
                            .log(Level.SEVERE, null, ex);
                }

                jasper.showViewer();    
                
            }
            
         
    }//GEN-LAST:event_jlButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportesInformativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportesInformativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportesInformativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportesInformativos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportesInformativos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker Dp1;
    private org.jdesktop.swingx.JXDatePicker Dp2;
    private Main.JlComboBox cmbRep;
    private Main.JlButton jlButton1;
    // End of variables declaration//GEN-END:variables
}
